In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# Importing the dataset
import pandas as pd
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [6]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


In [9]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
# Feature Scaling
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
# Menggunakan ColumnTransformer dan OneHotEncoder untuk meng-encode variabel kategori
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2])], remainder='passthrough')
X = ct.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

buat ANN

In [14]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [15]:
# Initialising the ANN
classifier = Sequential()

In [16]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

c:\Users\aryas\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from keras.models import Sequential
from keras.layers import Dense

# Mengimpor dataset
dataset = pd.read_csv('Churn_Modelling.csv')

# Memisahkan fitur dan target
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# Mengonversi variabel kategori menjadi variabel numerik menggunakan OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2])], remainder='passthrough')
X = ct.fit_transform(X)

# Membagi dataset menjadi Training set dan Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Melakukan feature scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Periksa bentuk data setelah preprocessing
print(X_train.shape)
print(X_test.shape)

# Membuat model ANN
classifier = Sequential()

# Menambahkan input layer dan hidden layer pertama
classifier.add(Dense(units=6, activation='relu', input_dim=X_train.shape[1]))

# Menambahkan hidden layer kedua
classifier.add(Dense(units=6, activation='relu'))

# Menambahkan output layer
classifier.add(Dense(units=1, activation='sigmoid'))

# Kompilasi ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Melatih ANN pada Training set
classifier.fit(X_train, y_train, batch_size=10, epochs=20)


# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 20)

(8000, 13)
(2000, 13)
Epoch 1/20


c:\Users\aryas\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 563us/step - accuracy: 0.7530 - loss: 0.5120
Epoch 2/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.8004 - loss: 0.4382
Epoch 3/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - accuracy: 0.8326 - loss: 0.3974
Epoch 4/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - accuracy: 0.8430 - loss: 0.3846
Epoch 5/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.8470 - loss: 0.3675
Epoch 6/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step - accuracy: 0.8569 - loss: 0.3457
Epoch 7/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.8519 - loss: 0.3513
Epoch 8/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step - accuracy: 0.8599 - loss: 0.3458
Epoch 9/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step - accuracy: 0.8606 - loss: 0.3425
Epoch 10/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.8660 - loss: 0.3349
Epoch 11/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - accuracy: 0.8618 - loss: 0.3392
Epoch 12/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 

buat prediksi dan evaluasi model

In [19]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred_ = (y_pred > 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step


In [20]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_)

In [21]:
cm

array([[1517,   78],
       [ 199,  206]], dtype=int64)

In [22]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
y_pred_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [24]:
y_pred

array([[0.17798965],
       [0.377602  ],
       [0.12349191],
       ...,
       [0.360392  ],
       [0.14121826],
       [0.15260807]], dtype=float32)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred_)
print("Confusion Matrix:\n", cm)

# Menghitung metrik performa
accuracy = accuracy_score(y_test, y_pred_)
precision = precision_score(y_test, y_pred_)
recall = recall_score(y_test, y_pred_)
f1 = f1_score(y_test, y_pred_)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Confusion Matrix:
 [[1517   78]
 [ 199  206]]
Accuracy: 0.8615
Precision: 0.7253521126760564
Recall: 0.508641975308642
F1 Score: 0.5979680696661829
